# Generated by Django 3.1.1 on 2020-09-10 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
