# Generated by Django 3.1.1 on 2020-09-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image2',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(upload_to='portfolio/images/'),
        ),
    ]
