# Generated by Django 3.1.1 on 2020-09-10 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20200910_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.FileField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
